### ISSUE TITLE
how did you import NestjsPaypalPayoutsModule? in order to use it?

### ISSUE THREAD

**Issue by SaramZafar** [LA/nestjs-paypal-payouts#1]
I am trying to import NestjsPaypalPayoutsModule but couldn't see any clue in docs nor in the readme. Please let me know how to import it?

**Comment by LA** [comment]
@SaramZafar You only need to import NestjsPaypalPayoutsModule into your module that you'd like to access PayPal with. Then you will have access to both @InjectPaypal and @InjectPaypalClient decorators, which should be all you need. FYI: I haven't used this package in prod, so no guarantees to its effectiveness, but it is purely a wrapper around Paypal's client, so should be fine.

**Comment by SaramZafar** [comment]
Thank you! I really appreciate your answer and I know how can I use it in the module.  but I am unable to import NestjsPaypalPayoutsModule from any path.  let me show you the code


**import {NestjsPaypalPayoutsModule} from 'What to write here? I couldn't find the path to specify here auto path is also not working'**

**Comment by LA** [comment]
@SaramZafar Oh I see. Should be able to import from `nestjs-paypal-payouts`, same as the npm module: https://www.npmjs.com/package/nestjs-paypal-payouts. Hopefully that works :)

**Comment by SaramZafar** [comment]
@LA  Well I know it is obvious to import it from 'nestjs-paypal-payouts'. I think my IDE (VScode) has some settings problem or something due to which I am unable to import it. :) btw, thank you!

You can close it! :)
